# Основные сообщения
TITLE = "WINDOWS ФАЙЛОВЫЙ АРХЕОЛОГ"
YEAR_2142 = "2142 год. Обнаружен древний сервер с Windows"
ERROR_WINDOWS_ONLY = "ОШИБКА: Эта программа работает только на Windows!"
CURRENT_OS = "Текущая ОС: {os}"
PROGRAM_EXIT = "Завершение программы..."
PRESS_ENTER_EXIT = "Нажмите Enter для выхода..."
PRESS_ENTER_CONTINUE = "Нажмите Enter для продолжения..."

# Навигация
CURRENT_DRIVE = "Текущий диск: {drive}"
CURRENT_PATH = "Текущий путь: {path}"
AVAILABLE_DRIVES = "Доступные диски: {drives}"
HELP_COMMAND = "Для справки введите 'help'"

# Меню
MAIN_MENU_TITLE = "КОМАНДЫ:"
LIST_CONTENTS = "1. Список содержимого каталога"
ANALYZE_DIR = "2. Анализ каталога"
SEARCH_FILES = "3. Поиск файлов"
ADVANCED_ANALYSIS = "4. Расширенный анализ"
MOVE_UP = "5. На уровень выше"
MOVE_DOWN = "6. В подкаталог"
SPECIAL_FOLDERS = "7. Специальные папки Windows"
CHANGE_DRIVE = "8. Сменить диск"
EXIT_PROGRAM = "0. Выход"
HELP_MENU = "help - Показать справку"

# Навигационные сообщения
MOVED_TO = "Перешли в: {path}"
ALREADY_ROOT = "Уже в корне диска"
FAILED_LIST_DIR = "Не удалось получить содержимое каталога"
NO_SUBDIRS = "В этом каталоге нет подкаталогов"
AVAILABLE_SUBDIRS = "Доступные подкаталоги:"
ENTER_NUMBER_OR_NAME = "Введите номер или имя папки:"
INVALID_NUMBER = "Неверный номер"
FAILED_MOVE = "Не удалось перейти в '{dir}'"
SELECT_DRIVE = "Выберите диск (номер или буква):"
DRIVE_UNAVAILABLE = "Диск {drive} недоступен"
DRIVE_NOT_FOUND = "Диск {drive} не найден"
SWITCHED_DRIVE = "Переключились на диск {drive}"
NO_SPECIAL_FOLDERS = "Не удалось получить специальные папки"
WINDOWS_SPECIAL_FOLDERS = "Специальные папки Windows:"
ENTER_FOLDER_NUMBER = "Введите номер папки для перехода (или Enter для отмены):"
PATH_UNAVAILABLE = "Путь недоступен: {error}"
MOVE_TO_FOLDER = "Переход в {name}: {path}"

# Анализ
DIRECTORY_STATS = "Статистика каталога: {path}"
BASIC_STATS = "Базовая статистика каталога: {path}"
ADVANCED_STATS = "Расширенный анализ каталога: {path}"
ANALYSIS_ERROR = "Ошибка при анализе каталога"
GENERAL_INFO = "Общая информация:"
FILES_COUNT = "Файлов: {count}"
TOTAL_SIZE = "Размер: {size}"
FILE_TYPES = "Типы файлов:"
FILE_ATTRIBUTES = "Атрибуты файлов:"
LARGEST_FILES = "Самые большие файлы:"
ANALYSIS_COMPLETE = "Анализ завершен успешно"
ANALYSIS_ERROR_MSG = "Ошибка анализа: {error}"

# Счетчики
COUNT_FILES_SIZE = "Подсчет файлов и размера:"
TOTAL_FILES = "Файлов: {count}"
TOTAL_SIZE_BYTES = "Общий размер: {size}"
FILE_TYPE_STATS = "Статистика по типам файлов:"
FILE_ATTRIB_STATS = "Атрибуты файлов:"
FILES_WITH_ATTRS = "Файлы с особыми атрибутами не найдены"

# Поиск
SEARCH_MENU = "Меню поиска (текущий путь: {path})"
STARTING_SEARCH = "Запуск поискового меню..."
RETURN_MAIN_MENU = "Возврат в главное меню..."
SEARCH_PATTERN = "Поиск файлов по шаблону '{pattern}' в {path}..."
FILES_FOUND = "Найдено файлов: {count}"
SEARCH_COMPLETE = "Поиск завершен. Найдено {found} из ~{total} файлов"
PATH_ERROR = "Ошибка пути: {error}"
SEARCH_ERROR = "Ошибка при поиске: {error}"
SEARCH_EXTENSIONS = "Поиск файлов с расширениями {extensions}..."
LARGE_FILES_SEARCH = "Поиск файлов размером > {size} MB..."
LARGE_FILES_FOUND = "Найдено крупных файлов: {count}"
SYSTEM_FILES_SEARCH = "Поиск системных файлов Windows..."
SYSTEM_FILES_FOUND = "Найдено системных файлов: {count}"
SCANNING_FOLDER = "Сканирование {folder}..."

# Результаты поиска
SEARCH_RESULTS = "Результаты поиска ({count} файлов):"
NO_FILES_FOUND = "Файлы не найдены"
EXTENSIONS_INPUT = "Введите расширения через запятую (exe, dll, pdf):"
MIN_SIZE_INPUT = "Минимальный размер в MB (например, 100):"
INVALID_SIZE = "Размер должен быть положительным числом!"
INVALID_NUMBER_FORMAT = "Неверный формат числа!"
LARGE_FILES_TOTAL = "Найдено {count} файлов > {size} MB:"
TOTAL_SIZE_MB = "Общий размер: {size:.2f} MB"
LARGEST_FILE = "Самый большой файл: {name} ({size:.2f} MB)"
NO_LARGE_FILES = "Крупные файлы не найдены"
NO_SYSTEM_FILES = "Системные файлы не найдены"
FILE_TYPE_DISTRIBUTION = "Распределение по типам:"
CONTINUE_SEARCH = "Продолжить поиск? (y/N):"
INVALID_CHOICE = "Неверный выбор! Попробуйте снова."

# Вывод результатов
NO_RESULTS = "Результаты не найдены"
AND_MORE_FILES = "... и еще {count} файлов"
TOTAL_FILES_COUNT = "Всего файлов: {count}"
FILE_ATTRIB_SAMPLE = "Атрибуты файлов (на основе выборки):"
TOTAL_SYSTEM_FILES = "Всего системных файлов: {count}"

# Сканирование безопасности
SECURITY_SCAN = "Сканирование безопасности..."
SECURITY_SCAN_COMPLETE = "Сканирование завершено. Найдено угроз: {count}"
SECURITY_RESULTS = "Результаты сканирования:"

# Справка
HELP_TITLE = "СПРАВКА ПО КОМАНДАМ"
SHOW_CONTENTS = "1 - Показать файлы и папки в текущем каталоге"
BASIC_STATISTICS = "2 - Базовая статистика каталога"
SEARCH_MENU_HELP = "3 - Меню поиска (по шаблону, расширению, размеру)"
ADVANCED_STATISTICS = "4 - Расширенная статистика (подробный анализ)"
GO_PARENT = "5 - Перейти в родительский каталог"
GO_SUBDIR = "6 - Перейти в подкаталог (выбрать из списка)"
SPECIAL_FOLDERS_HELP = "7 - Показать и перейти в специальные папки Windows"
CHANGE_DRIVE_HELP = "8 - Сменить текущий диск"
EXIT_HELP = "0 - Выйти из программы"

# Общие
UNKNOWN_COMMAND = "Неизвестная команда: '{command}'"
ENTER_HELP = "Введите 'help' для списка команд"
EXIT_PROGRAM_CONFIRM = "Выход из программы..."
THANK_YOU = "Спасибо за использование Windows Файлового Археолога!"
INTERRUPTED = "Прервано (Ctrl+C)"
EXIT_CONFIRM = "Выйти из программы? (y/N):"
EXITING = "Выход..."
CRITICAL_ERROR = "Критическая ошибка: {error}"
PROGRAM_COMPLETE = "Программа завершена. До свидания!"

# Список содержимого
DIRECTORY_CONTENTS = "Содержимое каталога: {path}"
TOTAL_ITEMS = "Всего элементов: {count}"
EMPTY_DIRECTORY = "Каталог пуст"

# Форматирование
TYPE = "Тип"
SIZE = "Размер"
MODIFIED = "Модифицирован"
HIDDEN = "Скрытый"
NAME = "Имя"
FOLDER = "<Папка>"
YES = "Да"
NO = "Нет"

# Ошибки валидации
ONLY_WINDOWS = "Программа работает только на Windows"
TOO_MANY_COLONS = "Слишком много двоеточий в пути"
COLON_POSITION = "Двоеточие должно быть на второй позиции (C:)"
INVALID_DRIVE = "Неверное обозначение диска"
MISSING_BACKSLASH = "После обозначения диска должен быть обратный слеш (C:\\)"
FORBIDDEN_CHAR = "Запрещенный символ в пути: {char}"
PATH_TOO_LONG = "Путь превышает максимальную длину 260 символов"
FUNCTION_WINDOWS_ONLY = "Функция работает только в Windows"
MAX_RECURSION_DEPTH = "Превышена максимальная глубина рекурсии"

# Анализ структуры
DIRECTORY_ANALYSIS = "АНАЛИЗ СТРУКТУРЫ КАТАЛОГОВ"
TOTAL_ELEMENTS = "Всего элементов: {count}"
LEVEL = "Ур."
TYPE_COL = "Тип"
PATH_COL = "Путь"
STATISTICS = "СТАТИСТИКА"
NO_DATA = "Нет данных для отображения"

# Навигация с историей
START_NAVIGATION = "НАЧАЛО НАВИГАЦИИ: {path}"
PRESS_ENTER_CONTINUE_NAV = "Нажмите Enter для продолжения, 'q' для выхода"
CURRENT_PATH_NAV = "Текущий путь: {path}"
HISTORY_DEPTH = "Глубина в истории: {depth}"
FOLDERS_COUNT = "Папок: {folders}, Файлов: {files}"
COMMAND_PROMPT = "Команда (Enter - продолжить, q - выйти):"
NAVIGATION_END = "Завершение навигации"
NAVIGATION_ERROR = "Ошибка при навигации: {error}"

# Экспорт
TREE_EXPORTED = "Дерево экспортировано в {filename}"
EXPORT_ERROR = "Ошибка при экспорте: {error}"
ANALYSIS_SAVED = "Анализ сохранен в {filename}"
SAVE_ERROR = "Ошибка при сохранении: {error}"

# Поиск контента
CONTENT_SEARCH = "Поиск текста '{pattern}'..."
CONTENT_FILES_FOUND = "Найдено файлов: {count}"
SMART_SEARCH = "Умный поиск: '{query}'..."

# Поисковая справка
SEARCH_HELP_TITLE = "СПРАВКА ПО ПОИСКУ WINDOWS"
SEARCH_PATTERNS = "Шаблоны поиска:"
WINDOWS_EXTENSIONS = "Расширения Windows:"
EXECUTABLES = "Исполняемые: .exe, .bat, .cmd, .msi"
SYSTEM_FILES = "Системные: .dll, .sys, .drv, .ocx"
DOCUMENTS = "Документы: .docx, .xlsx, .pptx, .pdf"
SCRIPTS = "Скрипты: .ps1, .vbs, .js"
SECURITY_SCAN_HELP = "Безопасность:"
SECURITY_CHECKS = "Сканирование проверяет:"

# Меню поиска
SEARCH_MENU_TITLE = "МЕНЮ ПОИСКА WINDOWS"
SEARCH_OPTION_PATTERN = "1. Поиск файлов по шаблону (*.txt, *test*, etc)"
SEARCH_OPTION_EXT = "2. Поиск по расширениям (.exe, .dll, .pdf, etc)"
SEARCH_OPTION_SIZE = "3. Поиск крупных файлов"
SEARCH_OPTION_SYSTEM = "4. Поиск системных файлов Windows"
SEARCH_OPTION_STATS = "5. Статистика текущего каталога"
SEARCH_OPTION_RETURN = "6. Вернуться в главное меню"
CHOOSE_OPTION = "Выберите опцию (1-6):"
PATTERN_INPUT = "Введите шаблон поиска (например, *.txt):"
PATTERN_EMPTY = "Шаблон не может быть пустым!"
CASE_SENSITIVE = "Чувствительность к регистру? (y/N):"
EXTENSIONS_EMPTY = "Нужно указать хотя бы одно расширение!"
EMPTY_RESULTS = "Файлы не найдены"